### ISSUE TITLE
RM's personal wishlist for LifePlay (will be updated from time to time)

### ISSUE THREAD

**Issue by robert-monotoli** [vinfamy/LifePlay#179]
Hello! I thought I'd make an index of my ideas. Will update this from time to time, so keep eyes out for that! Comments will be added to announce any updates for this post.

Note: Some of the items here will have a link to an "issue", where the idea is expanded upon.

### Gameplay
- [ ] Add outdoor locations such as beaches, swimming pools, parks, etc. (butt secks on the beach! 😜 )
- [ ] Expanded mechanics for business, work, and finance. Stocks and what-not.
- [ ] More careers and jobs. Career system could be a rank-and-ladder. A career may be made up of different jobs that corresponds to a rank. To make it even more interesting, a career may have two or more branches. For example, law enforcement career may have detective and patrol branches.
- [ ] Traits system for the characters. See [here](https://github.com/vinfamy/LifePlay/issues/174) for more information.
- [ ] Favorites system. See [here](https://github.com/vinfamy/LifePlay/issues/175) for more information.
- [ ] Additional place types: Casino, city hall, and newspaper office. More to add later.
- [ ] More to add here!

### Interface
- [ ] New mapping system for a city (already have been discussed at length at the Discord server). Should permit a player to build their own city and personalize it. Allow us to add street names and district names that can be used in events. Address numbers may be automatically generated for purposes such as answering a call when working as a police officer or a detective.
- [ ] Tooltips for actions should display text for modifiers in appropriate color. Positive modifier should be green and negative modifier should be red.
- [ ] Each option during a event scene should display a tooltip listing the effects for that option, similar to how it worked in Europa Universalis 4 for an event. However, they may be hidden by default, with an option in the setting to toggle it on or off.
- [ ] Add more 3D rooms
- [ ] Change clothes interface should be similar to Create A Sim in The Sims 4. All clothing items should be categorized into collapsible tabs such as Bras, Underwear, Accessories, etc. Then you should be able to set Outfits for specific circumstances such as Everyday, Formal, Athletic, Sleep, Party, Swimwear, Hot Weather, and Cold Weather.
- [ ] A shopping cart interface to display what you have brought so far while shopping at a place.
- [ ] An interface displaying a list of total modifier values for each stat (e.g. fertility from birth control; perversion from clothing; etc.)
- [ ] Improved save file management system. More information [here](https://github.com/vinfamy/LifePlay/issues/177).
- [ ] More to add here!

### Modding
- [ ] Modding: Add a trigger for a specific date or a specific month; useful for holidays such as Christmas and Thanksgiving.
- [ ] More to add here!

### Assorted
- [ ] When 3D bathroom is added, enable sex scenes there. Not all sex positions may be appropriate for various parts of the room so it should be context-specific. Missionary would probably not be comfortable in bathtub. 😛 
- [ ] Add relationship level status (as opposed to relationship status) that indicates the person's perception of your character: Stranger, Acquaintance, Friend, Best Friend or Close Friend, Lover, Married. Certain levels would be locked out for certain circumstances where it may be inappropriate. For example, stranger would not make sense for a family relative.
- [ ] More to add here!

Again, I will update this from time to time.

**Comment by robert-monotoli** [comment]
Changelog for this issue from today, including certain changes from yesterday:

- **EDIT**: Added "sex shop", "adult cinema", and "museum" for the additional place types
- **EDIT**: Deleted "Certain levels would be locked out for certain circumstances where it may be inappropriate. For example, stranger would not make sense for a family relative."
- **ADD**: "Additional clothing items: Open version of bras (exposing breasts but still on), garter belts (a waist band with suspenders), etc."
- **ADD**: "Incestuous Tension stat value for a given NPC should be displayed on the Contacts information for that NPC. No need to go into Edit Stats to see it."
- **ADD**: "Sex scene interface should display whether your female character or female NPC is on birth control pill; constantly checking to see if "take a birth control" action is greyed out or not can be tedious and you cannot even check that during a sex scene. It may be represented as an icon at the edge of the scene screen."
- **ADD**: "Action to cook a meal FOR the household. Should be able to do this only once per a meal period in any day: breakfast, lunch, and dinner."
- **ADD**: "Service NPCs such as maid/butler."

**Comment by robert-monotoli** [comment]
Changelog for this issue from today:
ADD: Added "A ponytail over the shoulder for females. Here are examples one, two, three, four, and five to illustrate what is meant by that."
UPDATE: "Tanlines" now checkmarked after its implementation in v4.0 beta 2.
